#include "Token.hpp"

const char *kindToString(const Token::Kind kind) {
  using enum Token::Kind;
  switch (kind) {
  case Integer:
    return "Integer";
  case FloatingPoint:
    return "FloatingPoint";
  case Plus:
    return "Plus";
  case PlusEquals:
    return "PlusEquals";
  case Minus:
    return "Minus";
  case MinusEquals:
    return "MinusEquals";
  case LeftParen:
    return "LeftParen";
  case RightParen:
    return "RightParen";
  case LeftSquareBracket:
    return "LeftSquareBracket";
  case RightSquareBracket:
    return "RightSquareBracket";
  case LeftCurly:
    return "LeftCurly";
  case RightCurly:
    return "RightCurly";
  case Semicolon:
    return "Semicolon";
  case Colon:
    return "Colon";
  case Comma:
    return "Comma";
  case Dot:
    return "Dot";
  case Asterisk:
    return "Asterisk";
  case AsteriskEquals:
    return "AsteriskEquals";
  case Slash:
    return "Slash";
  case SlashEquals:
    return "SlashEquals";
  case Percent:
    return "Percent";
  case Identifier:
    return "Identifier";
  case If:
    return "If";
  case Else:
    return "Else";
  case Equals:
    return "Equals";
  case DoubleEquals:
    return "DoubleEquals";
  case AmpersandAmpersand:
    return "AmpersandAmpersand";
  case BarBar:
    return "BarBar";
  case ExclamationMark:
    return "ExclamationMark";
  case ExclamationMarkEquals:
    return "ExclamationMarkEquals";
  case EqualsGreaterThan:
    return "EqualsGreaterThan";
  case LessThan:
    return "LessThan";
  case GreaterThan:
    return "GreaterThan";
  case LessThanEquals:
    return "LessThanEquals";
  case GreaterThanEquals:
    return "GreaterThanEquals";
  case Return:
    return "Return";
  case Function:
    return "Function";
  case Interface:
    return "Interface";
  case Let:
    return "Let";
  case String:
    return "String";
  case Char:
    return "Char";
  case Declare:
    return "Declare";
  case For:
    return "For";
  case True:
    return "True";
  case False:
    return "False";
  case End:
    return "End";
  case Unexpected:
    return "Unexpected";
  }
}